[package]
name = "asterix-deku"
version = "0.1.0"
authors = ["wcampbell"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deku = { git = "https://github.com/sharksforarms/deku.git", branch = "master" }
